WebSite/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    # Session
    path('debug', views.DebugFormView.as_view(), name='debug'),
    path('debug/clean_images', views.debug_clean_images, name='debug_clean_images'),
    path('debug/clean_cocuments', views.debug_clean_documents, name='debug_clean_documents'),
]

WebSite/reports/urls.py
from django.urls import path

from . import views
from .reports import finance
from .reports import sales
from .reports import volunteer

app_name = "reports"

urlpatterns = [
    # Selection
    path('select/<str:category>', views.select, name = 'select'),
    path('select/<str:category>/<str:report_name>', views.select, name = 'select_report'),
    # AJAX
    path('ajax/venue/<str:venue_id>/date/<str:date>/performances', views.ajax_venue_date_performances, name = 'ajax_venue_date_performances'),
    # Finance reports
    path('finance/festival_summary', finance.festival_summary, name = 'finance_festival_summary'),
    path('finance/boxoffice_summary', finance.boxoffice_summary, name = 'finance_boxoffice_summary'),
    path('finance/venue_summary', finance.venue_summary, name = 'finance_venue_summary'),
    path('finance/refunds', finance.refunds, name = 'finance_refunds'),
    path('finance/company_payment', finance.company_payment, name = 'finance_company_payment'),
    path('finance/company_payw', finance.company_payw, name = 'finance_company_payw'),
    # Sales reports
    path('sales/audience', sales.audience, name = 'sales_audience'),
    path('sales/admission_lists', sales.admission_lists, name = 'sales_admission_lists'),
    path('sales/tickets_by_type', sales.tickets_by_type, name = 'sales_tickets_by_type'),
    path('sales/tickets_by_channel', sales.tickets_by_channel, name = 'sales_tickets_by_channel'),
    # Volunteer reports
    path('volunteer/shifts', volunteer.shifts_pdf, name = 'volunteer_shifts_pdf'),
    path('volunteer/<uuid:volunteer_uuid>/shifts', volunteer.shifts_pdf, name = 'volunteer_shifts_pdf'),
    # Old reports
    path('sale/<uuid:sale_uuid>/pdf', finance.sale_pdf, name = 'sale_pdf'),
    path('refund/<uuid:refund_uuid>/pdf', finance.refund_pdf, name = 'refund_pdf'),
    path('admission/<uuid:performance_uuid>/pdf', finance.admission_pdf, name = 'admission_pdf'),
]

WebSite/venue/urls.py
from django.urls import path

from . import views

app_name = "venue"

urlpatterns = [
    # Select
    path('select', views.select, name = 'select'),
    # Main page
    path('<uuid:venue_uuid>', views.main, name = 'main'),
    path('<uuid:venue_uuid>/performance/<uuid:performance_uuid>', views.main_performance, name = 'main_performance'),
    path('<uuid:venue_uuid>/performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>', views.main_performance_sale, name = 'main_performance_sale'),
    # Open/close checkpoint API
    path('performance/<uuid:performance_uuid>/open', views.performance_open, name = 'performance_open'),
    path('performance/<uuid:performance_uuid>/close', views.performance_close, name = 'performance_close'),
    path('checkpoint/<uuid:checkpoint_uuid>/update_open', views.checkpoint_update_open, name = 'checkpoint_update_open'),
    path('checkpoint/<uuid:checkpoint_uuid>/update_close', views.checkpoint_update_close, name = 'checkpoint_update_close'),
    # Sale API
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/select', views.sale_select, name = 'sale_select'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/close', views.sale_close, name = 'sale_close'),
    path('performance/<uuid:performance_uuid>/sale/start', views.sale_start, name = 'sale_start'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/items', views.sale_items, name = 'sale_items'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/payment/card', views.sale_payment_card, name = 'sale_payment_card'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/complete/zero', views.sale_complete_zero, name = 'sale_complete_zero'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/cancel', views.sale_cancel, name = 'sale_cancel'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/update', views.sale_update, name = 'sale_update'),
    # Tickets API
    path('performance/<uuid:performance_uuid>/tickets/refresh', views.tickets_refresh, name = 'tickets_refresh'),
    path('performance/<uuid:performance_uuid>/ticket/<uuid:ticket_uuid>/token', views.tickets_token, name = 'tickets_token'),
    path('performance/<uuid:performance_uuid>/badges', views.tickets_badges, name = 'tickets_badges'),
    path('performance/<uuid:performance_uuid>/tickets/print', views.tickets_print, name = 'tickets_print'),
    # Info API
    path('performance/<uuid:performance_uuid>/info', views.performance_info, name = 'performance_info'),
    # Square callback
    path('square/callback', views.square_callback, name='square_callback'),
]

WebSite/venue/models.py
from django.db import models

# Create your models here.

WebSite/venue/views.py
import json

from decimal import Decimal

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import transaction
from django.db.models import Q, Sum
from django.db.models.functions import Coalesce
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import View
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.csrf import csrf_exempt
from django.forms import formset_factory, modelformset_factory
from django.utils import timezone

import arrow

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, HTML, Submit, Button, Row, Column
from crispy_forms.bootstrap import FormActions, TabHolder, Tab, Div

from django_htmx.http import HttpResponseClientRedirect

from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4, portrait
from reportlab.lib.units import cm
from reportlab.lib import colors

from core.models import User
from program.models import Show, ShowPerformance, Venue
from tickets.models import Sale, TicketType, Ticket, FringerType,  Fringer, Checkpoint, BadgesIssued
from .forms import OpenCheckpointForm, SaleItemsForm, SaleUpdateForm, CloseCheckpointForm

# Logging
import logging
logger = logging.getLogger(__name__)

# SquareUp interface
def get_square_intent(request, venue, performance, sale):

    # Only create intent if card payment (SquareUp) pending
    if sale and sale.is_payment_pending and sale.is_square:
        metadata = f'{{ "venue_id": {venue.id}, "performance_id": {performance.id}, "sale_id": {sale.id} }}'
        callback_url = request.build_absolute_uri(reverse('venue:square_callback'))
        intent = ';'.join([
            'intent:#Intent',
            'package=com.squareup',
            'action=com.squareup.pos.action.CHARGE',
            f'S.com.squareup.pos.WEB_CALLBACK_URI={callback_url}',
            f'S.com.squareup.pos.CLIENT_ID={settings.SQUARE_APPLICATION_ID}',
            f'S.com.squareup.pos.API_VERSION={settings.SQUARE_API_VERSION}',
            f'i.com.squareup.pos.TOTAL_AMOUNT={sale.total_cost_pence}',
            f'S.com.squareup.pos.CURRENCY_CODE={settings.SQUARE_CURRENCY_CODE}',
            'S.com.squareup.pos.TENDER_TYPES=com.squareup.pos.TENDER_CARD',
            f'S.com.squareup.pos.NOTE={sale.id}',
            f'S.com.squareup.pos.REQUEST_METADATA={metadata}',
            'end'
        ])
    else:
        intent = ''
    return intent

@require_GET
def square_callback(request):

    # Get parameters
    server_transaction_id = request.GET.get('com.squareup.pos.SERVER_TRANSACTION_ID', None)
    client_transaction_id = request.GET.get('com.squareup.pos.CLIENT_TRANSACTION_ID', None)
    request_metadata = request.GET.get('com.squareup.pos.REQUEST_METADATA', None)
    error_code = request.GET.get('com.squareup.pos.ERROR_CODE', None)
    error_description = request.GET.get('com.squareup.pos.ERROR_DESCRIPTION', None)

    # Parse meta-data
    metadata = json.loads(request_metadata)
    venue = get_object_or_404(Venue, pk=metadata['venue_id'])
    performance = get_object_or_404(ShowPerformance, pk=metadata['performance_id'])
    sale = get_object_or_404(Sale, pk=metadata['sale_id'])

    # Check for errors
    if error_code:

        # Reset payment type
        sale.amount = 0
        sale.transaction_type = None
        sale.transaction_fee = 0
        sale.save()
        logger.info(f"Square callback error (sale {sale.id}): {error_description}")
        if error_code == 'com.squareup.pos.ERROR_TRANSACTION_CANCELED':
            messages.warning(request, "Card payment cancelled")
        else:
            messages.error(request, f"Card payment failed: {error_description}")
    
        # Display main page with the sale still selected
        return redirect(reverse('venue:main_performance_sale', args=[venue.uuid, performance.uuid, sale.uuid]))

    # Tokens for venue ticket sales are issued immediately
    for ticket in sale.tickets.all():
        ticket.token_issued = True
        ticket.save()

    # Complete the sale
    sale.transaction_ID = server_transaction_id
    sale.completed = timezone.now()
    sale.save()
    logger.info(f"Sale {sale.id} completed (SQuareUp)")
    messages.success(request, "Card payment completed")

    # Display main page for new sale
    return redirect(reverse('venue:main_performance', args=[venue.uuid, performance.uuid]))


# Helpers
def is_next(performance):

    # Validate parameters
    assert performance

    # Check if this is the next performance at the venue
    return performance == performance.venue.get_next_performance(performance.date)


# Select venue
@require_GET
@user_passes_test(lambda u: u.is_venue or u.is_admin)
@login_required
def select(request):
    context = {
        'venues': Venue.objects.filter(festival=request.festival, is_ticketed=True),
    }
    return render(request, 'venue/select.html', context)


# Main page - open tab
def open_form(performance, post_data = None):

    # Validate parameters
    assert performance

    # Create form
    checkpoint = performance.open_checkpoint if performance.has_open_checkpoint else None
    form = OpenCheckpointForm(checkpoint, data = post_data)

    # Add crispy form helper
    form.helper = FormHelper()
    form.helper.form_id = 'open-form'
    form.helper.layout = Layout(
        Row(
            Column('buttons', css_class='form-group col-md-4 mb-0'),
            Column('fringers', css_class='form-group col-md-4 mb-0'),
        ),
        Field('notes'),
    )

    # Return form
    return form

def open_context(request, venue, performance, form=None):

    # Validate parameters
    assert performance

    # Create context
    return {
        'venue': venue,
        'performance': performance,
        'open_form': form or open_form(performance),
    }

def render_open(request, venue, performance, form=None):

    # Validate parameters
    assert performance

    # Create context and render open tab content
    context = open_context(request, venue, performance, form)
    context['tab'] = 'open'
    return render(request, "venue/_main_open.html", context)

@require_POST
@login_required
@user_passes_test(lambda u: u.is_venue or u.is_admin)
@transaction.atomic
def performance_open(request, performance_uuid):

    # Get performance and venue
    performance = get_object_or_404(ShowPerformance, uuid = performance_uuid)
    assert not performance.has_open_checkpoint
    assert not performance.has_close_checkpoint
    venue = performance.venue

    # Process open form
    form = open_form(performance, request.POST)
    if form.is_valid():

        # Create open checkpoint
        checkpoint = Checkpoint(
            user = request.user,
            venue = venue,
            open_performance = performance,
            cash = 0,
            buttons = form.cleaned_data['buttons'],
            fringers = form.cleaned_data['fringers'],
            notes = form.cleaned_data['notes'],
        )
        checkpoint.save()
        logger.info(f"Open checkpoint created at {venue.name} for {performance.show.name} on {performance.date} at {performance.time}")
        messages.success(request, 'Performance opened')
        return HttpResponseClientRedirect(reverse('venue:main_performance', args=[venue.uuid, performance.uuid]))
    
    # Form has errors
    return render_open(request, venue, performance, form)

@require_POST
@login_required
@user_passes_test(lambda u: u.is_venue or u.is_admin)
@transaction.atomic
def checkpoint_update_open(request, checkpoint_uuid):

    # Get checkpoint, venue and performance
    checkpoint = get_object_or_404(Checkpoint, uuid = checkpoint_uuid)
    venue = checkpoint.venue
    assert venue
    performance = checkpoint.open_performance
    assert performance
    assert performance.venue == venue

    # Process checkpoint form
    form = open_form(performance, request.POST)
    if form.is_valid():

        # Update checkpoint
        checkpoint.notes = form.cleaned_data['notes']
        checkpoint.save()
        logger.info(f"Open checkpoint updated at {venue.name} for {performance.show.name} on {performance.date} at {performance.time}")
        messages.success(request, "Checkpoint updated")
        form = None

    # Render page
    return render_open(request, venue, performance, form)

# Main page - sales tab
def sale_items_form(performance, sale, post_data = None):

    # Validate parameters
    assert performance
    assert sale

    # Only create form if sale is in progress
    form = None
    if sale.is_in_progress:

        ## Additional parameter checks
        assert performance.has_open_checkpoint
        assert not performance.has_close_checkpoint
        assert is_next(performance)
        
        # Get initial values from sale
        initial_data = {
            'buttons': sale.buttons,
            'fringers': sale.fringers.count(),
        }

        # Get ticket types and add initial values
        ticket_types = []
        for ticket_type in sale.festival.ticket_types.filter(is_venue=True).order_by('seqno'):
            ticket_types.append(ticket_type)
            initial_data[SaleItemsForm.ticket_field_name(ticket_type)] = sale.tickets.filter(type=ticket_type).count()

        # Create form
        form = SaleItemsForm(ticket_types, data = post_data, initial = initial_data)

        # Add crispy form helper
        form.helper = FormHelper()
        form.helper.form_id = 'sale-items-form'
        form.helper.form_class = 'form-horizontal'
        form.helper.label_class = 'col-6'
        form.helper.field_class = 'col-6'

WebSite/templates/venue/_main_close.html
{% load crispy_forms_tags %}

{% if tab == 'close' %}
    {% for msg in messages %}
        <div class="{{ msg.tags }} alert-dismissible" role="alert">
            {{ msg }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
    {% endfor %}
{% endif %}

<div class="row">
    <div class="col-12 col-md-6 mb-2">
        <div class="card">
            <h6 class="card-header">Checkpoint</h6>
            <div class="card-body">
                {% if close_form %}
                    {% crispy close_form %}
                    {% if performance.has_close_checkpoint %}
                        <button class="btn btn-primary" hx-post="{% url 'venue:checkpoint_update_close' performance.close_checkpoint.uuid %}" hx-include="#close-form">Update</button>
                    {% else %}
                        <button class="btn btn-primary" hx-post="{% url 'venue:performance_close' performance.uuid %}" hx-include="#close-form">Close</button>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-12 col-md-6 mb-2">
        <div class="alert alert-info">
            <p>You must complete the close checkpoint before you can move on to the next show:</p>
            <ul>
                <li>Badges - number of fringe badges</li>
                <li>Fringers - number of paper fringers</li>
                <li>Audience - number of audience tokens collected</li>
            </ul>
            <p>You can also add any notes that may be useful.</p>
            <p><strong>Important:</strong> once the performance has been closed you cannot update the badges or fringers but you can still add/update the audience and notes.</p>
        </div>
    </div>
</div>

WebSite/templates/venue/_main_open.html
{% load crispy_forms_tags %}

{% if tab == 'open' %}
    {% for msg in messages %}
        <div class="{{ msg.tags }} alert-dismissible" role="alert">
            {{ msg }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
    {% endfor %}
{% endif %}

<div class="row" hx-target="#open-tab-content">
    <div class="col-12 col-md-6 mb-2">
        <div class="card">
            <h6 class="card-header">Checkpoint</h6>
            <div class="card-body">
                {% if open_form %}
                    {% crispy open_form %}
                    {% if performance.has_open_checkpoint %}
                        <button class="btn btn-primary" hx-post="{% url 'venue:checkpoint_update_open' performance.open_checkpoint.uuid %}" hx-include="#open-form">Update</button>
                    {% else %}
                        <button class="btn btn-primary" hx-post="{% url 'venue:performance_open' performance.uuid %}" hx-include="#open-form">Open</button>
                    {% endif %}
                {% else %}
                    <p>You cannot open this performance until all previous performances have been closed.</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-12 col-md-6 mb-2">
        <div class="alert alert-info">
            <p>You must complete the open checkpoint before you can make sales and process admissions for this show:</p>
            <ul>
                <li>Badges - number of fringe badges</li>
                <li>Fringers - number of paper fringers</li>
            </ul>
            <p>You can also add any notes that may be useful.</p>
            <p><strong>Important:</strong> once the performance has been opened you cannot update the badges or fringers but you can still add/update the notes.</p>
        </div>
    </div>
</div>

WebSite/templates/venue/_main_sales.html
{% load crispy_forms_tags %}

<style>
    .legend {
        font-size: 1em;
        font-weight: bold;
    }
    div.alert-danger ul {
        margin-bottom: 0;
        list-style-type: none;
        padding-left: 0;
    }
</style>

{% if tab == 'sales' %}
    {% for msg in messages %}
        <div class="{{ msg.tags }} alert-dismissible" role="alert">
            {{ msg }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
    {% endfor %}
{% endif %}

<div class="row" hx-target="#sales-tab-content">

    <div class="col-6">
        {% if not performance.has_open_checkpoint %}
            <div class="alert alert-info">
                <p>This performance has not been opened.</p>
            </div>
        {% elif not performance.has_close_checkpoint and not sale %}
            <div class="card mb-2">
                <h6 class="card-header">New Sale</h6>
                <div class="card-body">
                    <div class="alert alert-info">
                        <p>To start a new sale click Start.</p>
                    </div>
                    <button class="btn btn-primary" hx-get="{% url 'venue:sale_start' performance.uuid %}">Start</button>
                </div>
            </div>
        {% elif sale.is_complete %}
            <div class="card">
                <h6 class="card-header">Sale: {{ sale.id }}</h6>
                <div class="card-body">
                    <div class="alert alert-info">
                        {% for performance in sale.ticket_performances %}
                            <div class="row mb-2">
                                <div class="col-12"><strong>{{ performance.show }}</strong></div>
                                <div class="col-12">{{ performance.date | date:'D, j M' }} at {{ performance.time | time:'h:ia' }}</div>
                                <div class="col-12">
                                    {% for ticket in performance.tickets %}
                                        <div class="row">
                                            <div class="col-1"></div>
                                            <div class="col-8">{{ ticket.description }}</div>
                                            <div class="col-3 text-right">{% if ticket.cost %}&#163;{{ ticket.cost }}{% endif %}</div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endfor %}
                        {% if sale.buttons %}
                            <div class="row mb-2">
                                <div class="col-9"><strong>{{ sale.buttons }} x Badges</strong></div>
                                <div class="col-3 text-right">&#163;{{ sale.button_cost }}</div>
                            </div>
                        {% endif %}
                        {% if sale.fringers.count > 0 %}
                            <div class="row mb-2">
                                <div class="col-9"><strong>{{ sale.fringers.count }} x Paper fringers ({{ sale.festival.fringer_shows }} shows for &#163;{{ sale.festival.fringer_price | floatformat:0 }})</strong></div>
                                <div class="col-3 text-right">&#163;{{ sale.fringer_cost }}</div>
                            </div>
                        {% endif %}
                        <div class="row mb-2">
                            <div class="col-9"><strong>Total</strong></div>
                            <div class="col-3 text-right">&#163;{{ sale.total_cost }}</div>
                        </div>
                        {% if sale.transaction_type %}
                            <div class="row mb-2">
                                <div class="col-9"><strong>Payment type</strong></div>
                                <div class="col-3 text-right">{{ sale.transaction_type_description }}</div>
                            </div>
                        {% endif %}
                    </div>
                    {% if sale_form %}
                        {% crispy sale_form %}
                        <button class="btn btn-primary" hx-post="{% url 'venue:sale_update' performance.uuid sale.uuid %}" hx-include="#sale-form">Update</button>
                    {% endif %}
                    <div class="float-right">
                        <button class="btn btn-secondary" hx-get="{% url 'venue:sale_close' performance.uuid sale.uuid %}">Close</button>
                    </div>
                </div>
            </div>
        {% elif performance.has_close_checkpoint %}
            <div class="alert alert-info">
                <p>This performance is now closed.</p>
            </div>
        {% elif sale_items_form %}
            <div class="card mb-2">
                <h6 class="card-header">New Sale<div class="float-right">Available: {{ available }}</div></h6>
                <div class="card-body">
                    {% crispy sale_items_form %}
                    <button class="btn btn-primary" hx-post="{% url 'venue:sale_items' performance.uuid sale.uuid %}" hx-include="#sale-items-form">Add/Update Sale</button>
                </div>
            </div>
        {% elif sale.is_square %}
            <div class="alert alert-warning">
                <p>Square POS App.</p>
                <p>
                    The Square App should have opened automatically to handle the card payment.
                    If that has not happened you can complete the sale manually (without payment) by selecting the Complete button.
                </p>
            </div>
        {% endif %}
    </div>
    <div class="col-6">
        {% if not sale or sale.is_complete %}
            <div class="card">
                <h6 class="card-header">All Sales</h6>
                <div class="card-body">
                    <div class="alert alert-info">
                        <p>Select a sale to view the details and add/update notes.</p>
                    </div>
                    <table class="table table-striped">
                        <thhead>
                            <tr>
                                <th>Sale No</th>
                                <th>Time</th>
                                <th>Amount</th>
                            </tr>
                        </thhead>
                        <tbody>
                            {% for sale in sales %}
                                <tr>
                                    <td><a href="#" hx-get="{% url "venue:sale_select" performance.uuid sale.uuid %}">{{ sale.id }}</a></td>
                                    <td>{{ sale.completed.time }}</td>
                                    <td>&#163;{{ sale.amount }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <div class="card">
                <h6 class="card-header">Sale: {{ sale.id }}</h6>
                <div class="card-body">
                    <div class="alert alert-info">
                        {% if sale_form %}
                            <p>Once all items have been added select the payment type to complete the sale.</p>
                        {% else %}
                            <p>Select Complete when payment has been received or Cancel if you want to update the sale or change the payment type.</p>
                        {% endif %}
                    </div>
                    {% for performance in sale.ticket_performances %}
                        <div class="row mb-2">
                            <div class="col-12"><strong>{{ performance.show }}</strong></div>
                            <div class="col-12">{{ performance.date | date:'D, j M' }} at {{ performance.time | time:'h:ia' }}</div>
                            <div class="col-12">
                                {% for ticket in performance.tickets %}
                                    <div class="row">
                                        <div class="col-1"></div>
                                        <div class="col-8">{{ ticket.description }}</div>
                                        <div class="col-3 text-right">{% if ticket.cost %}&#163;{{ ticket.cost }}{% endif %}</div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                    {% if sale.buttons %}
                        <div class="row mb-2">
                            <div class="col-9"><strong>{{ sale.buttons }} x Badges</strong></div>
                            <div class="col-3 text-right">&#163;{{ sale.button_cost }}</div>
                        </div>
                    {% endif %}
                    {% if sale.fringers.count > 0 %}
                        <div class="row mb-2">
                            <div class="col-9"><strong>{{ sale.fringers.count }} x Paper fringers ({{ sale.festival.fringer_shows }} shows for &#163;{{ sale.festival.fringer_price | floatformat:0 }})</strong></div>
                            <div class="col-3 text-right">&#163;{{ sale.fringer_cost }}</div>
                        </div>
                    {% endif %}
                    <div class="row mb-2">
                        <div class="col-9"><strong>Total</strong></div>
                        <div class="col-3 text-right">&#163;{{ sale.total_cost }}</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-12">
                            {% if sale.is_in_progress %}
                                {% crispy sale_form %}
                                {% if sale.total_cost > 0 %}
                                    <button class="btn btn-primary" hx-post="{% url 'venue:sale_payment_card' performance.uuid sale.uuid %}" hx-include="#sale-form">Card</button>
                                {% elif not sale.is_empty %}
                                    <button class="btn btn-primary" hx-post="{% url 'venue:sale_complete_zero' performance.uuid sale.uuid %}" hx-include="#sale-form">Complete</button>
                                {% endif %}
                                <div class="float-right">
                                    <button class="btn btn-secondary" hx-get="{% url 'venue:sale_cancel' performance.uuid sale.uuid %}">Cancel</button>
                                </div>
                            {% elif sale.is_square %}
                                <button class="btn btn-primary" onclick="squareUpComplete()">Complete</button>
                                <div class="float-right">
                                    <button class="btn btn-secondary" onclick="squareUpCancel()">Cancel</button>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

</div>

<script language="javascript">

    // The following are used for testing only
    function squareUpMetadata() {
        return "{ \"venue_id\": {{venue.id}}, \"performance_id\": {{performance.id}}, \"sale_id\": {{sale.id}} }";
    }

    function squareUpComplete() {
        var url =
            "{% url 'venue:square_callback' %}" +
            "?com.squareup.pos.SERVER_TRANSACTION_ID=" +
            "&com.squareup.pos.CLIENT_TRANSACTION_ID=" +
            "&com.squareup.pos.REQUEST_METADATA=" + squareUpMetadata() +
            "&com.squareup.pos.ERROR_CODE=" +
            "&com.squareup.pos.ERROR_DESCRIPTION=";
        window.location = url;
    }

    function squareUpCancel() {
        var url =
            "{% url 'venue:square_callback' %}" +
            "?com.squareup.pos.SERVER_TRANSACTION_ID=" +
            "&com.squareup.pos.CLIENT_TRANSACTION_ID=" +
            "&com.squareup.pos.REQUEST_METADATA=" + squareUpMetadata() +
            "&com.squareup.pos.ERROR_CODE=com.squareup.pos.ERROR_TRANSACTION_CANCELED" +
            "&com.squareup.pos.ERROR_DESCRIPTION=*Cancelled*";
        window.location = url;
    }

    // If ready to accept card payment switch to the SquareUp POS app
    {% if square_intent %}
        window.location = '{{square_intent|safe}}';
    {% endif %}

</script>

WebSite/templates/venue/select.html
{% extends "base.html" %}

{% block pagetitle %}Select Venue{% endblock %}

{% block banner %}{% endblock %}

{% block content %}

    <ul>
        {% for venue in venues %}
            <li><a class="btn btn-default" href="{% url 'venue:main' venue.uuid %}">{{ venue.name }}</a></li>
        {% endfor %}
    </ul>


{% endblock %}