WebSite/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    # Session
    path('debug', views.DebugFormView.as_view(), name='debug'),
    path('debug/clean_images', views.debug_clean_images, name='debug_clean_images'),
    path('debug/clean_cocuments', views.debug_clean_documents, name='debug_clean_documents'),
]

WebSite/program/urls.py
from django.urls import path

from . import views

app_name = "program"

urlpatterns = [
    path('shows', views.shows, name = 'shows'),
    path('show', views.shows, name = 'show_obsolete'),
    path('shows/<uuid:festival_uuid>', views.shows, name = 'shows'),
    path('show/<uuid:show_uuid>', views.show, name = 'show'),
    path('schedule', views.schedule, name = 'schedule'),
    path('schedule/<uuid:festival_id>', views.schedule, name = 'schedule'),
    path('schedule/pdf', views.schedule_pdf, name = 'schedule_pdf'),
    path('schedule/<uuid:festival_uuid>/pdf', views.schedule_pdf, name = 'schedule_pdf'),
    path('venues', views.venues, name = 'venues'),
    path('venues/<uuid:festival_uuid>', views.venues, name = 'venues'),
    path('venue/<uuid:venue_uuid>', views.venue, name = 'venue'),
    path('admin/genre/list', views.AdminGenreList.as_view(), name='admin_genre_list'),
    path('admin/genre/create', views.AdminGenreCreate.as_view(), name='admin_genre_create'),
    path('admin/genre/copy', views.admin_genre_copy, name='admin_genre_copy'),
    path('admin/genre/<uuid:slug>/update', views.AdminGenreUpdate.as_view(), name='admin_genre_update'),
    path('admin/genre/<uuid:slug>/delete', views.admin_genre_delete, name='admin_genre_delete'),
    path('admin/venue/list', views.AdminVenueList.as_view(), name='admin_venue_list'),
    path('admin/venue/create', views.AdminVenueCreate.as_view(), name='admin_venue_create'),
    path('admin/venue/copy', views.admin_venue_copy, name='admin_venue_copy'),
    path('admin/venue/<uuid:slug>/update', views.AdminVenueUpdate.as_view(), name='admin_venue_update'),
    path('admin/venue/<uuid:slug>/update/<tab>', views.AdminVenueUpdate.as_view(), name='admin_venue_update_tab'),
    path('admin/venue/<uuid:slug>/delete', views.admin_venue_delete, name='admin_venue_delete'),
    path('admin/venue/<uuid:venue_uuid>/contact/create', views.AdminVenueContactCreate.as_view(), name='admin_venue_contact_create'),
    path('admin/venue/<uuid:venue_uuid>/contact/<uuid:slug>/update', views.AdminVenueContactUpdate.as_view(), name='admin_venue_contact_update'),
    path('admin/venue/<uuid:venue_uuid>/contact/<uuid:slug>/delete', views.admin_venue_contact_delete, name='admin_venue_contact_delete'),
    path('admin/venue/<uuid:venue_uuid>/sponsor/create', views.AdminVenueSponsorCreate.as_view(), name='admin_venue_sponsor_create'),
    path('admin/venue/<uuid:venue_uuid>/sponsor/<uuid:slug>/update', views.AdminVenueSponsorUpdate.as_view(), name='admin_venue_sponsor_update'),
    path('admin/venue/<uuid:venue_uuid>/sponsor/<uuid:slug>/delete', views.admin_venue_sponsor_delete, name='admin_venue_sponsor_delete'),
    path('admin/company/list', views.AdminCompanyList.as_view(), name='admin_company_list'),
    path('admin/company/create', views.AdminCompanyCreate.as_view(), name='admin_company_create'),
    path('admin/company/<uuid:slug>/update', views.AdminCompanyUpdate.as_view(), name='admin_company_update'),
    path('admin/company/<uuid:slug>/update/<tab>', views.AdminCompanyUpdate.as_view(), name='admin_company_update_tab'),
    path('admin/company/<uuid:slug>/delete', views.admin_company_delete, name='admin_company_delete'),
    path('admin/company/<uuid:company_uuid>/contact/create', views.AdminCompanyContactCreate.as_view(), name='admin_company_contact_create'),
    path('admin/company/<uuid:company_uuid>/contact/<uuid:slug>/update', views.AdminCompanyContactUpdate.as_view(), name='admin_company_contact_update'),
    path('admin/company/<uuid:company_uuid>/contact/<uuid:slug>/delete', views.admin_company_contact_delete, name='admin_company_contact_delete'),
    path('admin/show/list', views.AdminShowList.as_view(), name='admin_show_list'),
    path('admin/show/create', views.AdminShowCreate.as_view(), name='admin_show_create'),
    path('admin/show/<uuid:slug>/update', views.AdminShowUpdate.as_view(), name='admin_show_update'),
    path('admin/show/<uuid:slug>/update/<tab>', views.AdminShowUpdate.as_view(), name='admin_show_update_tab'),
    path('admin/show/<uuid:slug>/delete', views.admin_show_delete, name='admin_show_delete'),
    path('admin/show/<uuid:show_uuid>/performance/create', views.AdminShowPerformanceCreate.as_view(), name='admin_show_performance_create'),
    path('admin/show/<uuid:show_uuid>/performance/<uuid:slug>/update', views.AdminShowPerformanceUpdate.as_view(), name='admin_show_performance_update'),
    path('admin/show/<uuid:show_uuid>/performance/<uuid:slug>/delete', views.admin_show_performance_delete, name='admin_show_performance_delete'),
    path('admin/show/<uuid:show_uuid>/review/create', views.AdminShowReviewCreate.as_view(), name='admin_show_review_create'),
    path('admin/show/<uuid:show_uuid>/review/<uuid:slug>/update', views.AdminShowReviewUpdate.as_view(), name='admin_show_review_update'),
    path('admin/show/<uuid:show_uuid>/review/<uuid:slug>/delete', views.admin_show_review_delete, name='admin_show_review_delete'),
    path('admin/show/<uuid:show_uuid>/image/create', views.AdminShowImageCreate.as_view(), name='admin_show_image_create'),
    path('admin/show/<uuid:show_uuid>/image/<uuid:slug>/update', views.AdminShowImageUpdate.as_view(), name='admin_show_image_update'),
    path('admin/show/<uuid:show_uuid>/image/<uuid:slug>/delete', views.admin_show_image_delete, name='admin_show_image_delete'),
]

WebSite/venue/urls.py
from django.urls import path

from . import views

app_name = "venue"

urlpatterns = [
    # Select
    path('select', views.select, name = 'select'),
    # Main page
    path('<uuid:venue_uuid>', views.main, name = 'main'),
    path('<uuid:venue_uuid>/performance/<uuid:performance_uuid>', views.main_performance, name = 'main_performance'),
    path('<uuid:venue_uuid>/performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>', views.main_performance_sale, name = 'main_performance_sale'),
    # Open/close checkpoint API
    path('performance/<uuid:performance_uuid>/open', views.performance_open, name = 'performance_open'),
    path('performance/<uuid:performance_uuid>/close', views.performance_close, name = 'performance_close'),
    path('checkpoint/<uuid:checkpoint_uuid>/update_open', views.checkpoint_update_open, name = 'checkpoint_update_open'),
    path('checkpoint/<uuid:checkpoint_uuid>/update_close', views.checkpoint_update_close, name = 'checkpoint_update_close'),
    # Sale API
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/select', views.sale_select, name = 'sale_select'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/close', views.sale_close, name = 'sale_close'),
    path('performance/<uuid:performance_uuid>/sale/start', views.sale_start, name = 'sale_start'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/items', views.sale_items, name = 'sale_items'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/payment/card', views.sale_payment_card, name = 'sale_payment_card'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/complete/zero', views.sale_complete_zero, name = 'sale_complete_zero'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/cancel', views.sale_cancel, name = 'sale_cancel'),
    path('performance/<uuid:performance_uuid>/sale/<uuid:sale_uuid>/update', views.sale_update, name = 'sale_update'),
    # Tickets API
    path('performance/<uuid:performance_uuid>/tickets/refresh', views.tickets_refresh, name = 'tickets_refresh'),
    path('performance/<uuid:performance_uuid>/ticket/<uuid:ticket_uuid>/token', views.tickets_token, name = 'tickets_token'),
    path('performance/<uuid:performance_uuid>/badges', views.tickets_badges, name = 'tickets_badges'),
    path('performance/<uuid:performance_uuid>/tickets/print', views.tickets_print, name = 'tickets_print'),
    # Info API
    path('performance/<uuid:performance_uuid>/info', views.performance_info, name = 'performance_info'),
    # Square callback
    path('square/callback', views.square_callback, name='square_callback'),
]

WebSite/venue/models.py
from django.db import models

# Create your models here.

WebSite/venue/forms.py
from django import forms
from django.core.exceptions import ValidationError

from tickets.models import TicketType, Checkpoint


class OpenCheckpointForm(forms.Form):

    buttons = forms.IntegerField(label = 'Badges', required = True, widget = forms.NumberInput(attrs = { 'style': 'width: 75px' }))
    fringers = forms.IntegerField(label = 'Fringers', required = True, widget = forms.NumberInput(attrs = { 'style': 'width: 75px' }))
    notes = forms.CharField(label = 'Notes', widget = forms.Textarea(attrs = { 'style': 'width:100%; height: 200px' }), required = False)

    def __init__(self, checkpoint, *args, **kwargs):
        if checkpoint:
            kwargs['initial'] = {
                'buttons': checkpoint.buttons,
                'fringers': checkpoint.fringers,
                'notes': checkpoint.notes,
            }
        super().__init__(*args, **kwargs)
        if checkpoint:
            self.fields['buttons'].disabled = True
            self.fields['fringers'].disabled = True


class SaleItemsForm(forms.Form):

    buttons = forms.IntegerField(label = 'Badges', required = True, initial = 0, min_value = 0, widget = forms.NumberInput(attrs = { 'style': 'width: 75px' }))
    fringers = forms.IntegerField(label = 'Paper fringers (buy)', required = True, initial = 0, min_value = 0, widget = forms.NumberInput(attrs = { 'style': 'width: 75px' }))
    volunteer = forms.BooleanField(label = 'Use volunteer ticket', required = False, initial = False)

    def __init__(self, ticket_types, *args, **kwargs):
        self.ticket_types = ticket_types
        super().__init__(*args, **kwargs)
        for tt in self.ticket_types:
            label = 'Paper fringer (use)' if tt.name == 'Fringer' else tt.name
            self.fields[self.ticket_field_name(tt)] = forms.IntegerField(label = label, required = True, initial = 0, min_value = 0, widget = forms.NumberInput(attrs = { 'style': 'width: 75px' }))
                
    @classmethod
    def ticket_field_name(cls, ticket_type):
        return f'ticket_{ticket_type.id}'

    @property
    def ticket_count(self):
        return (
            sum([self.cleaned_data[self.ticket_field_name(tt)] for tt in self.ticket_types])
        )


class SaleUpdateForm(forms.Form):

    notes = forms.CharField(label = 'Notes', widget = forms.Textarea(attrs = { 'style': 'width: 100%; height: 100px' }), required = False)

    def __init__(self, sale, *args, **kwargs):
        if sale:
            kwargs['initial'] = {
                'notes': sale.notes,
            }
        super().__init__(*args, **kwargs)

class CloseCheckpointForm(forms.Form):

    buttons = forms.IntegerField(label = 'Badges', required = True, widget = forms.NumberInput(attrs = { 'style': 'width: 75px' }))
    fringers = forms.IntegerField(label = 'Fringers', required = True, widget = forms.NumberInput(attrs = { 'style': 'width: 75px' }))
    audience = forms.IntegerField(label = 'Audience', required = False, widget = forms.NumberInput(attrs = { 'style': 'width: 75px' }))
    notes = forms.CharField(label = 'Notes', widget = forms.Textarea(attrs = { 'style': 'width: 100%; height: 200px' }), required = False)

    def __init__(self, checkpoint, *args, **kwargs):
        if checkpoint:
            kwargs['initial'] = {
                'buttons': checkpoint.buttons,
                'fringers': checkpoint.fringers,
                'audience': checkpoint.close_performance.audience,
                'notes': checkpoint.notes,
            }
        super().__init__(*args, **kwargs)
        if checkpoint:
            self.fields['buttons'].disabled = True
            self.fields['fringers'].disabled = True

WebSite/templates/program/_admin_company_contacts.html
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>Role</th>
            <th>TelNo</th>
        </tr>
    </thead>
    <tbody>
        {% for contact in company.contacts.all %}
            <tr>
                <td><a href="{% url 'program:admin_company_contact_update' company.uuid contact.uuid %}">{{ contact.name }}</a></td>
                <td>{{ contact.role }}</td>
                <td>{{ contact.telno }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="mb-4 text-right">
    <a class="btn btn-primary" href="{% url 'program:admin_company_contact_create' company.uuid %}">Add Contact</a>
</div>

WebSite/templates/program/_admin_show_images.html
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        {% for image in show.images.all %}
            <tr>
                <td><a href="{% url 'program:admin_show_image_update' show.uuid image.uuid %}">{{ image.name }}</a></td>
                <td></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="mb-4 text-right">
    <a class="btn btn-primary" href="{% url 'program:admin_show_image_create' show.uuid %}">Add Image</a>
</div>

WebSite/templates/program/_admin_venue_contacts.html
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>Role</th>
            <th>TelNo</th>
        </tr>
    </thead>
    <tbody>
        {% for contact in venue.contacts.all %}
            <tr>
                <td><a href="{% url 'program:admin_venue_contact_update' venue.uuid contact.uuid %}">{{ contact.name }}</a></td>
                <td>{{ contact.role }}</td>
                <td>{{ contact.telno }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="mb-4 text-right">
    <a class="btn btn-primary" href="{% url 'program:admin_venue_contact_create' venue.uuid %}">Add Contact</a>
</div>

WebSite/templates/program/admin_company.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Company{% endblock %}

{% block content %}

    {% crispy form %}

    {% if company.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this company?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'program:admin_company_list' %}'; });
        {% if company.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'program:admin_company_delete' company.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}
        {% if initial_tab %}
            $('.nav-tabs li a[href="#{{ initial_tab }}"]').tab('show');
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/program/admin_company_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Companies{% endblock %}

{% block content %}

<div class="row mb-2">
    <div class="col-3"><a href="{% url 'program:admin_company_create' %}" class="btn btn-primary">Add Company</a></div>
    <div class="col-9">
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                {% for company in companies %}
                    <tr>
                        <td><a href="{% url 'program:admin_company_update' company.uuid %}">{{ company.name }}</a></td>
                    </tr>
                {%endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

WebSite/templates/program/admin_genre.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Genre{% endblock %}

{% block content %}

    {% crispy form %}

    {% if genre.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this genre?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'program:admin_genre_list' %}'; });
        {% if genre.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'program:admin_genre_delete' genre.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/program/admin_show_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Shows{% endblock %}

{% block content %}

<div class="row mb-2">
    <div class="col-3"><a href="{% url 'program:admin_show_create' %}" class="btn btn-primary">Add Show</a></div>
    <div class="col-9">
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                    <th>Company</th>
                    <th>Venue(s)</th>
                </tr>
            </thead>
            <tbody>
                {% for show in shows %}
                    <tr>
                        <td><a href="{% url 'program:admin_show_update' show.uuid %}">{{ show.name }}</a></td>
                        <td>{{ show.company.name }}</td>
                        <td>{% for venue in show.performance_venues %}{{ venue.name }}<br/>{% endfor %}</td>
                    </tr>
                {%endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

WebSite/templates/program/admin_venue.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Venue{% endblock %}

{% block content %}

    {% crispy form %}

    {% if venue.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this venue?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'program:admin_venue_list' %}'; });
        {% if venue.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'program:admin_venue_delete' venue.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}
        {% if initial_tab %}
            $('.nav-tabs li a[href="#{{ initial_tab }}"]').tab('show');
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/program/admin_venue_contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Venue Contact{% endblock %}

{% block content %}

    {% crispy form %}

    {% if contact.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this contact?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'program:admin_venue_update_tab' venue.uuid 'contacts' %}'; });
        {% if contact.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'program:admin_venue_contact_delete' venue.uuid contact.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/program/admin_venue_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Venues{% endblock %}

{% block content %}

<div class="row mb-2">
    <div class="col-3"><a href="{% url 'program:admin_venue_create' %}" class="btn btn-primary">Add Venue</a></div>
    <div class="col-9">
        {% if festival.previous %}
            <form class="form-inline justify-content-end" method="post" action="{% url 'program:admin_venue_copy' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select class="form-control" name="copy_id">
                        <option value="0">Select venue to copy</option>
                        {% for venue in festival.previous.venues.all %}
                            <option value="{{ venue.id }}">{{ venue.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button class="btn btn-primary ml-2" type="submit">Copy from {{ festival.previous.name }}</button>
            </form>
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                    <th>Capacity</th>
                    <th>Sponsor</th>
                </tr>
            </thead>
            <tbody>
                {% for venue in venues %}
                    <tr>
                        <td><a href="{% url 'program:admin_venue_update' venue.uuid %}">{{ venue.name }}</a></td>
                        <td>{{ venue.capacity }}</td>
                        <td>{% if venue.sponsor %}{{ venue.sponsor.name }}{% endif %}</td>
                    </tr>
                {%endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

WebSite/templates/program/admin_venue_sponsor.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Venue Sponsor{% endblock %}

{% block content %}

    {% crispy form %}

    {% if sponsor.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this sponsor?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'program:admin_venue_update_tab' venue.uuid 'sponsors' %}'; });
        {% if sponsor.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'program:admin_venue_sponsor_delete' venue.uuid sponsor.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/program/schedule.html
{% extends "base.html" %}

{% block pagetitle %}times{% endblock %}

{% block content %}

    <div id="tf-program-schedule">

        <div class="text-right mb-3"><a class="btn btn-primary" href="{% url 'program:schedule_pdf' %}">Full schedule (PDF)</a></div>
        
        <div class="nav nav-pills nav-justified mb-3">
            {% for day in days %}
                <a class="nav-item nav-link {% if forloop.first %}active{% endif %}" href="#tab{{ forloop.counter }}" data-toggle="tab">{{ day.date | date:"l" }}</a>
            {% endfor %}
        </div>

        <div class="tab-content">
            {% for day in days %}
                <div id="tab{{ forloop.counter }}" class="tab-pane {% if forloop.first %}active{% endif %}">
                    <div class="row">
                        {% for venue in day.venues %}
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="mb-4 pl-2" {% if venue.color %}style="border-left: 1px solid {{ venue.color }};"{% endif %}>
                                    <h5 class="tf-venue-name" {% if venue.color %}style="color: {{ venue.color }};"{% endif %}>{{ venue.name }}</h5>
                                    <table class="table table-borderless table-sm">
                                        <colgroup>
                                            <col width="10%">
                                            <col width="90%">
                                        </colgroup>
                                        {% for performance in venue.performances %}
                                            {% if performance.is_cancelled %}
                                                <tr class="tf-cancelled">
                                                    <td>{{ performance.time | time:"H:i" }}</td>
                                                    <td>{{ performance.show_name }}</td>
                                                </tr>
                                            {% else %}
                                                <tr>
                                                    <td>{{ performance.time | time:"H:i" }}</td>
                                                    <td><a href="{% url 'program:show' performance.show_uuid %}">{{ performance.show_name }}</a></td>
                                                </tr>
                                            {% endif %}
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}