WebSite/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    # Session
    path('debug', views.DebugFormView.as_view(), name='debug'),
    path('debug/clean_images', views.debug_clean_images, name='debug_clean_images'),
    path('debug/clean_cocuments', views.debug_clean_documents, name='debug_clean_documents'),
]

WebSite/reports/urls.py
from django.urls import path

from . import views
from .reports import finance
from .reports import sales
from .reports import volunteer

app_name = "reports"

urlpatterns = [
    # Selection
    path('select/<str:category>', views.select, name = 'select'),
    path('select/<str:category>/<str:report_name>', views.select, name = 'select_report'),
    # AJAX
    path('ajax/venue/<str:venue_id>/date/<str:date>/performances', views.ajax_venue_date_performances, name = 'ajax_venue_date_performances'),
    # Finance reports
    path('finance/festival_summary', finance.festival_summary, name = 'finance_festival_summary'),
    path('finance/boxoffice_summary', finance.boxoffice_summary, name = 'finance_boxoffice_summary'),
    path('finance/venue_summary', finance.venue_summary, name = 'finance_venue_summary'),
    path('finance/refunds', finance.refunds, name = 'finance_refunds'),
    path('finance/company_payment', finance.company_payment, name = 'finance_company_payment'),
    path('finance/company_payw', finance.company_payw, name = 'finance_company_payw'),
    # Sales reports
    path('sales/audience', sales.audience, name = 'sales_audience'),
    path('sales/admission_lists', sales.admission_lists, name = 'sales_admission_lists'),
    path('sales/tickets_by_type', sales.tickets_by_type, name = 'sales_tickets_by_type'),
    path('sales/tickets_by_channel', sales.tickets_by_channel, name = 'sales_tickets_by_channel'),
    # Volunteer reports
    path('volunteer/shifts', volunteer.shifts_pdf, name = 'volunteer_shifts_pdf'),
    path('volunteer/<uuid:volunteer_uuid>/shifts', volunteer.shifts_pdf, name = 'volunteer_shifts_pdf'),
    # Old reports
    path('sale/<uuid:sale_uuid>/pdf', finance.sale_pdf, name = 'sale_pdf'),
    path('refund/<uuid:refund_uuid>/pdf', finance.refund_pdf, name = 'refund_pdf'),
    path('admission/<uuid:performance_uuid>/pdf', finance.admission_pdf, name = 'admission_pdf'),
]

WebSite/volunteers/urls.py
from django.urls import path

from . import views

app_name = 'volunteers'

urlpatterns = [
    # Volunteers
    path('shift/list', views.shift_list, name='shift_list'),
    path('shift/<uuid:slug>/accept', views.shift_accept, name='shift_accept'),
    path('shift/<uuid:slug>/cancel', views.shift_cancel, name='shift_cancel'),
    # Admin: Home
    path('admin/home', views.admin, name='admin_home'),
    # Admin: Roles
    path('admin/role/list', views.AdminRoleList.as_view(), name='admin_role_list'),
    path('admin/role/create', views.AdminRoleCreate.as_view(), name='admin_role_create'),
    path('admin/role/<uuid:slug>/update', views.AdminRoleUpdate.as_view(), name='admin_role_update'),
    path('admin/role/<uuid:slug>/delete', views.admin_role_delete, name='admin_role_delete'),
    # Admin: Locations
    path('admin/location/list', views.AdminLocationList.as_view(), name='admin_location_list'),
    path('admin/location/create', views.AdminLocationCreate.as_view(), name='admin_location_create'),
    path('admin/location/<uuid:slug>/update', views.AdminLocationUpdate.as_view(), name='admin_location_update'),
    path('admin/location/<uuid:slug>/delete', views.admin_location_delete, name='admin_location_delete'),
    # Admin: Commitmwents
    path('admin/commitment/list', views.AdminCommitmentList.as_view(), name='admin_commitment_list'),
    path('admin/commitment/create', views.AdminCommitmentCreate.as_view(), name='admin_commitment_create'),
    path('admin/commitment/<uuid:slug>/update', views.AdminCommitmentUpdate.as_view(), name='admin_commitment_update'),
    path('admin/commitment/<uuid:slug>/update/<str:tab>', views.AdminCommitmentUpdate.as_view(), name='admin_commitment_update_tab'),
    path('admin/commitment/<uuid:slug>/delete', views.admin_commitment_delete, name='admin_commitment_delete'),
    path('admin/commitment/<uuid:commitment_uuid>/shift/create', views.AdminCommitmentShiftCreate.as_view(), name='admin_commitment_shift_create'),
    path('admin/commitment/<uuid:commitment_uuid>/shift/<uuid:slug>/update', views.AdminCommitmentShiftUpdate.as_view(), name='admin_commitment_shift_update'),
    path('admin/commitment/<uuid:commitment_uuid>/shift/<uuid:slug>/delete', views.admin_commitment_shift_delete, name='admin_commitment_shift_delete'),
    # Admin: Shifts
    path('admin/shift/list', views.AdminShiftList.as_view(), name='admin_shift_list'),
    path('admin/shift/create', views.AdminShiftCreate.as_view(), name='admin_shift_create'),
    path('admin/shift/<uuid:slug>/update', views.AdminShiftUpdate.as_view(), name='admin_shift_update'),
    path('admin/shift/<uuid:slug>/delete', views.admin_shift_delete, name='admin_shift_delete'),
    # Admin: Volunteers
    path('admin/volunteers', views.admin_volunteers, name='admin_volunteers'),
    path('admin/volunteer/autocomplete', views.AdminVolunteerAutoComplete.as_view(), name='admin_volunteer_autocomplete'),
    path('admin/volunteer/<uuid:slug>/update', views.AdminVolunteerUpdate.as_view(), name='admin_volunteer_update'),
    path('admin/volunteer/<uuid:slug>/remove', views.admin_volunteer_remove, name='admin_volunteer_remove'),
]

WebSite/volunteers/views.py
import os
import datetime
import arrow

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.shortcuts import get_object_or_404, render, redirect
from django.template import Template, Context
from django.urls import reverse, reverse_lazy
from django.views.generic import View, ListView, CreateView, UpdateView

from dal.autocomplete import Select2QuerySetView

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, HTML, Submit, Button, Row, Column
from crispy_forms.bootstrap import FormActions, TabHolder, Tab

from core.models import User
from content.models import Document

from .models import Role, Location, Shift, Commitment, Volunteer
from .forms import (
    AdminRoleForm, AdminLocationForm, AdminShiftForm, AdminCommitmentForm,
    VolunteerAddForm, AdminVolunteerForm, VolunteerUserForm, VolunteerRolesForm,
    AdminShiftSearchForm,
)


# Logging
import logging
logger = logging.getLogger(__name__)


def render_shifts(request, volunteer):

    # Get available shifts
    shifts = Shift.objects.filter(location__festival=request.festival, volunteer_can_accept=True, volunteer__isnull=True, role__in=volunteer.roles.all())
    if volunteer.is_dbs == False:
        shifts = shifts.filter(needs_dbs = False)

    # Get days that have shifts defined
    days = []
    for day in shifts.order_by('date').values('date').distinct():
        days.append({
            'date': day['date'],
            'shifts': shifts.filter(date = day['date']).order_by('start_time')
        })
    context = {
        'my_shifts': volunteer.shifts.all(),
        'can_cancel': settings.VOLUNTEER_CANCEL_SHIFTS,
        'days': days,
    }

    # Get volunteer handbook URL
    handbook = Document.objects.filter(festival = request.festival, name='VolunteerHandbook').first()
    if handbook:
        context['handbook_url'] = handbook.get_absolute_url()

    # Render shifts
    return render(request, 'volunteers/shifts.html', context)

@login_required
def shift_list(request):

    # Get volunteer
    volunteer = request.user.volunteer

    # Render the page
    return render_shifts(request, volunteer)


@login_required
@transaction.atomic
def shift_accept(request, slug):

    # Get volunteer
    volunteer = request.user.volunteer

    # Get shift and assign to volunteer (if the shift is part of a commitment assign all shifts
    # in the commitment)
    shift = get_object_or_404(Shift, uuid=slug)
    if not shift.volunteer:
        if shift.commitment:
            shift.commitment.volunteer = volunteer
            shift.commitment.save()
            shift.commitment.update_shifts()
        else:
            shift.volunteer = volunteer
            shift.save()
        messages.success(request, 'Shift accepted')
    else:
        messages.error(request, 'Shift has been accepted by another volunteer')

    # Render the page
    return render_shifts(request, volunteer)


@login_required
@transaction.atomic
def shift_cancel(request, slug):

    # Get volunteer
    volunteer = request.user.volunteer

    # Get shift and de-assign
    shift = get_object_or_404(Shift, uuid=slug)
    if shift.volunteer == volunteer:
        shift.volunteer = None
        shift.save()
        messages.success(request, 'Shift cancelled')
    else:
        messages.error(request, 'Shift is assigned to another volunteer')

    # Render the page
    return render_shifts(request, volunteer)


@login_required
def admin(request):

    # Render the page
    context = {
        'festival': request.festival,
    }
    return render(request, 'volunteers/admin_home.html', context)


class AdminRoleList(LoginRequiredMixin, ListView):

    model = Role
    context_object_name = 'roles'
    template_name = 'volunteers/admin_role_list.html'

    def get_queryset(self):
        return Role.objects.filter(festival=self.request.festival)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['festival'] = self.request.festival
        context_data['breadcrumbs'] = [
            { 'text': 'Volunteer Admin', 'url': reverse('volunteers:admin_home') },
            { 'text': 'Roles' },
        ]
        return context_data


class AdminRoleCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = Role
    form_class = AdminRoleForm
    context_object_name = 'role'
    template_name = 'volunteers/admin_role.html'
    success_message = 'Role added'
    success_url = reverse_lazy('volunteers:admin_role_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['festival'] = self.request.festival
        return kwargs

    def get_form(self):
        form = super().get_form()
        form.fields['information'].widget.attrs['rows'] = 16
        form.helper = FormHelper()
        form.helper.layout = Layout(
            'description',
            'comps_per_shift',
            'information',
            FormActions(
                Submit('save', 'Save'),
                Button('cancel', 'Cancel'),
            ),
        )
        return form

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['festival'] = self.request.festival
        context_data['breadcrumbs'] = [
            { 'text': 'Volunteer Admin', 'url': reverse('volunteers:admin_home') },
            { 'text': 'Roles', 'url': reverse('volunteers:admin_role_list') },
            { 'text': 'Create' },
        ]
        return context_data


class AdminRoleUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Role
    form_class = AdminRoleForm
    slug_field = 'uuid'
    context_object_name = 'role'
    template_name = 'volunteers/admin_role.html'
    success_message = 'Role updated'
    success_url = reverse_lazy('volunteers:admin_role_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['festival'] = self.request.festival
        return kwargs

    def get_form(self):
        form = super().get_form()
        form.fields['information'].widget.attrs['rows'] = 16
        form.helper = FormHelper()
        form.helper.layout = Layout(
            'description',
            'comps_per_shift',
            'information',
            FormActions(
                Submit('save', 'Save'),
                Button('delete', 'Delete'),
                Button('cancel', 'Cancel'),
            )
        )
        return form

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['festival'] = self.request.festival
        context_data['breadcrumbs'] = [
            { 'text': 'Volunteer Admin', 'url': reverse('volunteers:admin_home') },
            { 'text': 'Roles', 'url': reverse('volunteers:admin_role_list') },
            { 'text': 'Update' },
        ]
        return context_data
    

@login_required
def admin_role_delete(request, slug):

    # Delete role
    role = get_object_or_404(Role, uuid=slug)
    role.delete()
    messages.success(request, 'Role deleted')
    return redirect('volunteers:admin_role_list')


class AdminLocationList(LoginRequiredMixin, ListView):

    model = Location
    context_object_name = 'locations'
    template_name = 'volunteers/admin_location_list.html'

    def get_queryset(self):
        return Location.objects.filter(festival=self.request.festival)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['festival'] = self.request.festival
        context_data['breadcrumbs'] = [
            { 'text': 'Volunteer Admin', 'url': reverse('volunteers:admin_home') },
            { 'text': 'Locations' },
        ]
        return context_data


class AdminLocationCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):

    model = Location
    form_class = AdminLocationForm
    context_object_name = 'location'
    template_name = 'volunteers/admin_location.html'
    success_message = 'Location added'
    success_url = reverse_lazy('volunteers:admin_location_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['festival'] = self.request.festival
        return kwargs

    def get_form(self):
        form = super().get_form()
        form.fields['information'].widget.attrs['rows'] = 16
        form.helper = FormHelper()
        form.helper.layout = Layout(
            'description',
            'information',
            FormActions(
                Submit('save', 'Save'),
                Button('cancel', 'Cancel'),
            ),
        )
        return form

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['festival'] = self.request.festival
        context_data['breadcrumbs'] = [
            { 'text': 'Volunteer Admin', 'url': reverse('volunteers:admin_home') },
            { 'text': 'Locations', 'url': reverse('volunteers:admin_location_list') },
            { 'text': 'Create' },
        ]
        return context_data


class AdminLocationUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = Location
    form_class = AdminLocationForm
    slug_field = 'uuid'
    context_object_name = 'location'
    template_name = 'volunteers/admin_location.html'
    success_message = 'Location updated'
    success_url = reverse_lazy('volunteers:admin_location_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['festival'] = self.request.festival
        return kwargs

    def get_form(self):
        form = super().get_form()
        form.fields['information'].widget.attrs['rows'] = 16

WebSite/templates/volunteers/admin.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Volunteers Administration{% endblock %}

{% block content %}

    <ul>
        <li><a href="{% url 'volunteers:admin_roles' %}">Roles</a></li>
        <li><a href="{% url 'volunteers:admin_locations' %}">Locations</a></li>
        <li><a href="{% url 'volunteers:admin_volunteers' %}">Volunteers</a></li>
        <li><a href="{% url 'volunteers:admin_shifts' %}">Shifts</a></li>
    </ul>

{% endblock %}

WebSite/templates/volunteers/admin_commitment.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Commitment{% endblock %}

{% block content %}

    {% crispy form %}

    {% if commitment.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this commitment?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'volunteers:admin_commitment_list' %}'; });
        {% if commitment.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'volunteers:admin_commitment_delete' commitment.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}
        {% if initial_tab %}
            $('.nav-tabs li a[href="#{{ initial_tab }}"]').tab('show');
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/volunteers/admin_commitment_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Commitments{% endblock %}

{% block content %}

    <table class="table">
        <thead class="thead-light">
            <tr>
                <th>Description</th>
                <th>Role</th>
                <th>Needs</th>
                <th>Shifts</th>
                <th>Volunteer</th>
            </tr>
        </thead>
        <tbody>
            {% for commitment in commitments %}
                <tr>
                    <td><a href="{% url 'volunteers:admin_commitment_update' commitment.uuid %}">{{ commitment.description }}</a></td>
                    <td>{{ commitment.role.description }}</td>
                    <td>{% if commitment.needs_dbs %}DBS{% endif %}</td>
                    <td>{{ commitment.shifts.count }}</td>
                    <td>{% if commitment.volunteer %}{{ commitment.volunteer.user.first_name }} {{ commitment.volunteer.user.last_name }}{% endif %}</td>
                </tr>
            {%endfor %}
        </tbody>
    </table>

    <a href="{% url 'volunteers:admin_commitment_create' %}" class="btn btn-primary">Add Commitment</a>

{% endblock %}

WebSite/templates/volunteers/admin_commitment_shift.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Commitment Shift{% endblock %}

{% block content %}

    {% crispy form %}

    {% if shift.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this commitment?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'volunteers:admin_commitment_update_tab' commitment.uuid 'shifts' %}'; });
        {% if shift.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'volunteers:admin_commitment_shift_delete' commitment.uuid shift.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/volunteers/admin_home.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Volunteer Administration: {{ request.festival.name }}{% endblock %}

{% block content %}

    <ul>
        <li><a href="{% url 'volunteers:admin_role_list' %}">Roles</a></li>
        <li><a href="{% url 'volunteers:admin_location_list' %}">Locations</a></li>
        <li><a href="{% url 'volunteers:admin_shift_list' %}">Shifts</a></li>
        <li><a href="{% url 'volunteers:admin_commitment_list' %}">Commitments</a></li>
        <li><a href="{% url 'volunteers:admin_volunteers' %}">Volunteers</a></li>
    </ul>

{% endblock %}

WebSite/templates/volunteers/admin_location_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Locations{% endblock %}

{% block content %}

    <table class="table">
        <thead class="thead-light">
            <tr>
                <th>Description</th>
                <th>Shifts</th>
            </tr>
        </thead>
        <tbody>
            {% for location in locations %}
                <tr>
                    <td><a href="{% url 'volunteers:admin_location_update' location.uuid %}">{{ location.description }}</a></td>
                    <td>{{ location.shifts.count }}</td>
                </tr>
            {%endfor %}
        </tbody>
    </table>

    <a href="{% url 'volunteers:admin_location_create' %}" class="btn btn-primary">Add Location</a>

{% endblock %}

WebSite/templates/volunteers/admin_role_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Roles{% endblock %}

{% block content %}

    <table class="table">
        <thead class="thead-light">
            <tr>
                <th>Description</th>
                <th>Comps</th>
                <th>Shifts</th>
                <th>Volunteers</th>
            </tr>
        </thead>
        <tbody>
            {% for role in roles %}
                <tr>
                    <td><a href="{% url 'volunteers:admin_role_update' role.uuid %}">{{ role.description }}</a></td>
                    <td>{{ role.comps_per_shift }}</td>
                    <td>{{ role.shifts.count }}</td>
                    <td>{{ role.volunteers.count }}</td>
                </tr>
            {%endfor %}
        </tbody>
    </table>

    <a href="{% url 'volunteers:admin_role_create' %}" class="btn btn-primary">Add Role</a>

{% endblock %}

WebSite/templates/volunteers/shifts.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Shifts{% endblock %}

{% block content %}

    <p>Selet a day to view and volunteer for shifts on that day.</p>

    <div class="nav nav-pills nav-justified mb-3">
        <a class="nav-item nav-link active" href="#tf-tab-myshifts" data-toggle="tab">My<br>Shifts</a>
        {% for day in days %}
            <a class="nav-item nav-link" href="#tf-tab-{{ day.date | date:'Ymd' }}" data-toggle="tab">{{ day.date | date:'l' }}<br>{{ day.date | date:'j F' }}</a>
        {% endfor %}
    </div>

    <div class="tab-content">

        <div id="tf-tab-myshifts" class="tab-pane fade show active">

            {% if not can_cancel %}
                <div class="alert alert-info">
                    You can no longer cancel shifts online. If you are unable to work a shift please e-mail Pete at volunteers@theatrefest.co.uk as soon as possible.
                </div>
            {% endif %}
            
            <div class="float-right">
                <a class="btn btn-primary" href="{% url 'reports:volunteer_shifts_pdf' %}" target="_blank">Print Shifts</a>
                {% if handbook_url %}
                    <a class="btn btn-primary" href="{{ handbook_url }}">Handbook PDF</a>
                {% endif %}
            </div>
            <div class="clearfix"></div>

            <table class="table accordion mt-2">
                <thead class="thead-light">
                    <tr>
                        <th>Date</th>
                        <th>Location</th>
                        <th>Time</th>
                        <th>Role</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for shift in my_shifts %}
                        <tr>
                            <td>{{ shift.date | date:'D, j M' }}</td>
                            <td>{{ shift.location.description }}</td>
                            <td>{{ shift.start_time | time:'g:i' }} - {{ shift.end_time | time:'g:iA' }}</td>
                            <td>{{ shift.role.description }}</td>
                            <td>{% if can_cancel %}<a href="{% url 'volunteers:shift_cancel' shift.uuid %}">Cancel</a>{% endif %}</td>
                            <td>{% if shift.notes %}<a href="#tf-tab-myshifts-{{ shift.id }}-notes" data-toggle="collapse"><i class="fa fa-info-circle"></i></a>{% endif %}</td>
                        </tr>
                        {% if shift.notes %}
                            <tr id="tf-tab-myshifts-{{ shift.id }}-notes" class="collapse" data-parent="#tf-tab-myshifts">
                                <td colspan="6" style="border: 0;"><div class="alert alert-info">{{ shift.notes | linebreaks }}</div></td>
                            </tr>
                        {% endif %}
                    {%endfor %}
                </tbody>
            </table>
        </div>

        {% for day in days %}
            <div id="tf-tab-{{ day.date | date:'Ymd' }}" class="tab-pane fade">
                <table class="table accordion">
                    <thead class="thead-light">
                        <tr>
                            <th></th>
                            <th>Location</th>
                            <th>Time</th>
                            <th>Role</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for shift in day.shifts %}
                            <tr>
                                <td>{% if shift.notes %}<a href="#tf-shift-{{ shift.id }}-notes" data-toggle="collapse"><i class="fa fa-info-circle"></i></a>{% endif %}</td>
                                <td>{{ shift.location.description }}</td>
                                <td>{{ shift.start_time | time:'g:i' }} - {{ shift.end_time | time:'g:iA' }}</td>
                                <td>{{ shift.role.description }}</td>
                                {% if shift.commitment %}
                                    <td><a href="#tf-shift-{{ shift.id }}-commitment" data-toggle="collapse">Commitment</a></td>
                                {% else %}
                                    <td><a href="{% url 'volunteers:shift_accept' shift.uuid %}">Accept</a></td>
                                {% endif %}
                            </tr>
                            {% if shift.commitment %}
                                <tr id="tf-shift-{{ shift.id }}-commitment" class="collapse" data-parent="#tf-tab-{{ day.date | date:'Ymd' }}">
                                    <td colspan="5" style="border: 0;"><div class="alert alert-warning">
                                        <p>By accepting this shift you are accepting all the following shifts.</p>
                                        <ul>
                                            {% for s in shift.commitment.shifts.all %}
                                                <li>{{ s.location.description }}, {{ s.date | date:'D, j M' }} {{ s.start_time | time:'g:i' }} - {{ s.end_time | time:'g:iA' }}, {{ s.role.description }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% if shift.commitment.notes %}
                                            <p>{{ shift.commitment.notes | linebreaks }}</p>
                                        {% endif %}
                                        <div>
                                            <a class="btn btn-primary" href="{% url 'volunteers:shift_accept' shift.uuid %}">Accept</a>
                                            <a class="btn btn-secondary" href="#tf-shift-{{ shift.id }}-commitment" data-toggle="collapse">Cancel</a>
                                        </div>
                                    </div></td>
                                </tr>
                            {% endif %}
                            {% if shift.notes %}
                                <tr id="tf-shift-{{ shift.id }}-notes" class="collapse" data-parent="#tf-tab-{{ day.date | date:'Ymd' }}">
                                    <td colspan="5" style="border: 0;"><div class="alert alert-info">{{ shift.notes | linebreaks }}</div></td>
                                </tr>
                            {% endif %}
                        {%endfor %}
                    </tbody>
                </table>
            </div>
        {% endfor %}

    </div>

{% endblock %}