WebSite/content/urls.py
from django.urls import path

from . import views

app_name = 'content'

urlpatterns = [
    # Pages
    path('page/<uuid:page_uuid>', views.page, name='page'),
    path('page/<uuid:page_uuid>/test', views.page_test, name='page_test'),
    path('page/<str:page_name>', views.page_name, name='page_name'),
    # Documents
    path('document/<uuid:document_uuid>', views.document, name='document'),
    # Resources
    path('resource/<uuid:resource_uuid>', views.resource, name='resource'),
    path('resource/<uuid:resource_uuid>/test', views.resource_test, name='resource_test'),
    # Administration
    path('admin/page/list', views.AdminPageList.as_view(), name='admin_page_list'),
    path('admin/page/create', views.AdminPageCreate.as_view(), name='admin_page_create'),
    path('admin/page/ccopy', views.admin_page_copy, name='admin_page_copy'),
    path('admin/page/<uuid:slug>/update', views.AdminPageUpdate.as_view(), name='admin_page_update'),
    path('admin/page/<uuid:slug>/update/<tab>', views.AdminPageUpdate.as_view(), name='admin_page_update_tab'),
    path('admin/page/<uuid:slug>/delete', views.admin_page_delete, name='admin_page_delete'),
    path('admin/page/<uuid:page_uuid>/image/create', views.AdminPageImageCreate.as_view(), name='admin_page_image_create'),
    path('admin/page/<uuid:page_uuid>/image/<uuid:slug>/update', views.AdminPageImageUpdate.as_view(), name='admin_page_image_update'),
    path('admin/page/<uuid:page_uuid>/image/<uuid:slug>/delete', views.admin_page_image_delete, name='admin_page_image_delete'),
    path('admin/navigator/list', views.AdminNavigatorList.as_view(), name='admin_navigator_list'),
    path('admin/navigator/create', views.AdminNavigatorCreate.as_view(), name='admin_navigator_create'),
    path('admin/navigator/<uuid:parent_uuid>/create', views.AdminNavigatorCreate.as_view(), name='admin_navigator_create_item'),
    path('admin/navigator/copy', views.admin_navigator_copy, name='admin_navigator_copy'),
    path('admin/navigator/<uuid:slug>/update', views.AdminNavigatorUpdate.as_view(), name='admin_navigator_update'),
    path('admin/navigator/<uuid:slug>/delete', views.admin_navigator_delete, name='admin_navigator_delete'),
    path('admin/image/list', views.AdminImageList.as_view(), name='admin_image_list'),
    path('admin/image/create', views.AdminImageCreate.as_view(), name='admin_image_create'),
    path('admin/image/copy', views.admin_image_copy, name='admin_image_copy'),
    path('admin/image/<uuid:slug>/update', views.AdminImageUpdate.as_view(), name='admin_image_update'),
    path('admin/image/<uuid:slug>/delete', views.admin_image_delete, name='admin_image_delete'),
    path('admin/document/list', views.AdminDocumentList.as_view(), name='admin_document_list'),
    path('admin/document/create', views.AdminDocumentCreate.as_view(), name='admin_document_create'),
    path('admin/document/copy', views.admin_document_copy, name='admin_document_copy'),
    path('admin/document/<uuid:slug>/update', views.AdminDocumentUpdate.as_view(), name='admin_document_update'),
    path('admin/document/<uuid:slug>/delete', views.admin_document_delete, name='admin_document_delete'),
    path('admin/resource/list', views.AdminResourceList.as_view(), name='admin_resource_list'),
    path('admin/resource/create', views.AdminResourceCreate.as_view(), name='admin_resource_create'),
    path('admin/resource/copy', views.admin_resource_copy, name='admin_resource_copy'),
    path('admin/resource/<uuid:slug>/update', views.AdminResourceUpdate.as_view(), name='admin_resource_update'),
    path('admin/resource/<uuid:slug>/delete', views.admin_resource_delete, name='admin_resource_delete'),
]

WebSite/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    # Session
    path('debug', views.DebugFormView.as_view(), name='debug'),
    path('debug/clean_images', views.debug_clean_images, name='debug_clean_images'),
    path('debug/clean_cocuments', views.debug_clean_documents, name='debug_clean_documents'),
]

WebSite/content/models.py
import os

from django.conf import settings
from django.db import models
from django.urls import reverse

from core.models import TimeStampedModel, Festival
from core.utils import get_image_filename, get_document_filename


class Page(TimeStampedModel):

    festival = models.ForeignKey(Festival, on_delete=models.CASCADE, related_name='pages')
    name = models.CharField(max_length=32)
    title = models.CharField(max_length=64, blank=True, default='')
    body = models.TextField(blank=True, default='')
    body_test = models.TextField(blank=True, default='')

    class Meta:
        ordering = ('festival', 'name')
        constraints = [
            models.UniqueConstraint(fields=['festival', 'name'], name='unique_page_name'),
        ]

    def __str__(self):
        return f'{self.festival.name}/{self.name}'

    def can_delete(self):
        return self.navigators.count() == 0

    def get_absolute_url(self):
        return reverse('content:page_name', args=[self.name.lower()])

    def get_test_url(self):
        return reverse('content:page_test', args=[self.uuid])

class PageImage(TimeStampedModel):

    page = models.ForeignKey(Page, on_delete = models.CASCADE, related_name = 'images')
    name = models.CharField(max_length = 32)
    image = models.ImageField(upload_to = get_image_filename, blank = True, default = '')

    class Meta:
        ordering = ('page', 'name')
        constraints = [
            models.UniqueConstraint(fields=['page', 'name'], name='unique_page_image_name'),
        ]

    def __str__(self):
        return f'{self.page}/{self.name}'

    def can_delete(self):
        return True

    def get_absolute_url(self):
        return os.path.join(getattr(settings, 'MEDIA_URL', '/media'), self.image.url)


class Navigator(TimeStampedModel):

    MENU = 0
    URL = 1
    PAGE = 2
    SHOWS = 3
    SCHEDULE = 4
    VENUES = 5
    ARCHIVE_INDEX = 6
    ARCHIVE_HOME = 7
    DONATIONS = 8
    TYPE_CHOICES = (
        (MENU, 'Menu'),
        (URL, 'URL'),
        (PAGE, 'Content page'),
        (SHOWS, 'List/Search shows'),
        (SCHEDULE, 'Schedule'),
        (VENUES, 'List venues'),
        (DONATIONS, 'Donations'),
        (ARCHIVE_INDEX, 'Archive index'),
        (ARCHIVE_HOME, 'Archive home'),
    )

    festival = models.ForeignKey(Festival, on_delete=models.CASCADE, related_name='navigators')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='items')
    seqno = models.PositiveIntegerField(blank=True, default=0)
    label = models.CharField(max_length=32)
    type = models.IntegerField(choices=TYPE_CHOICES)
    url = models.URLField(max_length=256, blank=True, default='')
    page = models.ForeignKey(Page, null=True, blank=True, on_delete=models.PROTECT, related_name='navigators')

    class Meta:
        ordering = ('festival', 'parent_id', 'seqno', 'label')
        constraints = [
            models.UniqueConstraint(fields=['festival', 'label'], condition=models.Q(parent__isnull=True), name='unique_root_navigator_label'),
            models.UniqueConstraint(fields=['festival', 'parent', 'label'], name='unique_navigator_item_label'),
        ]

    @property
    def href(self):
        if self.type == Navigator.URL and self.url:
            return self.url
        elif self.type == Navigator.PAGE and self.page:
            return self.page.get_absolute_url()
        elif self.type == Navigator.SHOWS:
            return reverse('program:shows')
        elif self.type == Navigator.SCHEDULE:
            return reverse('program:schedule')
        elif self.type == Navigator.VENUES:
            return reverse('program:venues')
        elif self.type == Navigator.DONATIONS:
            return reverse('tickets:donations')
        elif self.type == Navigator.ARCHIVE_INDEX:
            return reverse('festival:archive_index')
        elif self.type == Navigator.ARCHIVE_HOME:
            return reverse('festival:archive_home')
        else:
            return '#'

    def __str__(self):
        base = ''
        if (self.parent):
            base = f'{self.parent}'
        else:
            base = f'{self.festival.name}'
        return f'{base}/{self.label}'

    def is_menu(self):
        return (self.type == Navigator.MENU)
    
    def can_delete(self):
        return True


class Image(TimeStampedModel):

    festival = models.ForeignKey(Festival, on_delete=models.CASCADE, related_name='images')
    name = models.CharField(max_length=32)
    image = models.ImageField(upload_to = get_image_filename, blank = True, default = '')
    map = models.TextField(blank = True, default = '')

    class Meta:
        ordering = ('festival', 'name')
        constraints = [
            models.UniqueConstraint(fields=['festival', 'name'], name='unique_image_name'),
        ]

    def __str__(self):
        return f'{self.festival.name}/{self.name}'

    def can_delete(self):
        return True

    def get_absolute_path(self):
        return self.image.path

    def get_absolute_url(self):
        return os.path.join(getattr(settings, 'MEDIA_URL', '/media'), self.image.url)


class Document(TimeStampedModel):

    festival = models.ForeignKey(Festival, on_delete=models.CASCADE, related_name='documents')
    name = models.CharField(max_length=32)
    file = models.FileField(upload_to = get_document_filename, blank = True, default = '')
    filename = models.CharField(max_length=64, blank = True, default = '')

    class Meta:
        ordering = ('festival', 'name')
        constraints = [
            models.UniqueConstraint(fields=['festival', 'name'], name='unique_document_name'),
        ]

    def __str__(self):
        return f'{self.festival.name}/{self.name}'

    def can_delete(self):
        return True

    def get_absolute_url(self):
        return reverse('content:document', args=[self.uuid])


class Resource(TimeStampedModel):

    CSS = 'text/css'
    HTML = 'text/html'
    JAVASCRIPT = 'application/javascript'
    TYPE_CHOICES = (
        (CSS, 'CSS stylesheet'),
        (HTML, 'HTML template'),
        (JAVASCRIPT, 'Javascript'),
    )
    festival = models.ForeignKey(Festival, on_delete=models.CASCADE, related_name='resources')
    name = models.CharField(max_length=32)
    type = models.CharField(max_length=64, choices=TYPE_CHOICES)
    body = models.TextField(blank=True, default='')
    body_test = models.TextField(blank=True, default='')

    class Meta:
        ordering = ('festival', 'name')
        constraints = [
            models.UniqueConstraint(fields=['festival', 'name'], name='unique_resource_name'),
        ]

    def __str__(self):
        return f'{self.festival.name}/{self.name}'

    def can_delete(self):
        return True

    def get_absolute_url(self):
        return reverse('content:resource', args=[self.uuid])

    def get_test_url(self):
        return reverse('content:resource_test', args=[self.uuid])

WebSite/content/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Page, PageImage, Navigator, Image, Document, Resource


class AdminPageForm(forms.ModelForm):

    class Meta:
        model = Page
        fields = [
            'name',
            'title', 'body', 'body_test',
        ]
        labels = {
            'body': '',
            'body_test': '',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def validate_unique(self):
        super().validate_unique()
        try:
            self.instance.validate_constraints()
        except ValidationError:
            self._update_errors(ValidationError({'name': 'A page with that name already exists'}))


class AdminPageImageForm(forms.ModelForm):

    class Meta:
        model = PageImage
        fields = [
            'name',
            'image',
        ]

    def validate_unique(self):
        super().validate_unique()
        try:
            self.instance.validate_constraints()
        except ValidationError:
            self._update_errors(ValidationError({'name': 'An image with that name already exists for this page'}))


class AdminNavigatorForm(forms.ModelForm):

    class Meta:
        model = Navigator
        fields = [
            'seqno', 'label',
            'type', 'url', 'page',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['page'].queryset = Page.objects.filter(festival=self.instance.festival)

    # Same check - different error message (to avoid mention of festival)
    def validate_unique(self):
        super().validate_unique()
        try:
            self.instance.validate_constraints()
        except Exception as e: #ValidationError:
            if self.instance.parent:
               self._update_errors(ValidationError({'label': 'An item with that label already exists in this navigator'}))
            else:
                self._update_errors(ValidationError({'label': 'An navigator with that label already exists'}))

class AdminImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = [
            'name',
            'image',
            'map',
        ]

    def validate_unique(self):
        super().validate_unique()
        try:
            self.instance.validate_constraints()
        except ValidationError:
            self._update_errors(ValidationError({'name': 'An image with that name already exists'}))


class AdminDocumentForm(forms.ModelForm):

    class Meta:
        model = Document
        fields = [
            'name',
            'file', 'filename',
        ]

    def validate_unique(self):
        super().validate_unique()
        try:
            self.instance.validate_constraints()
        except ValidationError:
            self._update_errors(ValidationError({'name': 'A document with that name already exists'}))


class AdminResourceForm(forms.ModelForm):

    class Meta:
        model = Resource
        fields = [
            'name',
            'type',
            'body', 'body_test',
        ]

    def validate_unique(self):
        super().validate_unique()
        try:
            self.instance.validate_constraints()
        except ValidationError:
            self._update_errors(ValidationError({'name': 'A resource with that name already exists'}))

WebSite/templates/content/_admin_navigator_items.html
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>SeqNo</th>
            <th>Label</th>
        </tr>
    </thead>
    <tbody>
        {% for item in navigator.items.all %}
            <tr>
                <td>{{ item.seqno }}</td>
                <td><a href="{% url 'content:admin_navigator_update' item.uuid %}">{{ item.label }}</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="mb-4 text-right">
    <a class="btn btn-primary" href="{% url 'content:admin_navigator_create_item' navigator.uuid %}">Add Item</a>
</div>

WebSite/templates/content/_admin_page_images.html
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>Name</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        {% for image in page.images.all %}
            <tr>
                <td><a href="{% url 'content:admin_page_image_update' page.uuid image.uuid %}">{{ image.name }}</a></td>
                <td></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="mb-4 text-right">
    <a class="btn btn-primary" href="{% url 'content:admin_page_image_create' page.uuid %}">Add Image</a>
</div>

WebSite/templates/content/admin_document.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Document{% endblock %}

{% block content %}

    {% crispy form %}

    {% if document.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this document?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'content:admin_document_list' %}'; });
        {% if document.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'content:admin_document_delete' document.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}
        {% if initial_tab %}
            $('.nav-tabs li a[href="#{{ initial_tab }}"]').tab('show');
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/content/admin_document_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Documents{% endblock %}

{% block content %}

<div class="row mb-2">
    <div class="col-3"><a href="{% url 'content:admin_document_create' %}" class="btn btn-primary">Add Document</a></div>
    <div class="col-9">
        {% if festival.previous %}
            <form class="form-inline justify-content-end" method="post" action="{% url 'content:admin_document_copy' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select class="form-control" name="copy_id">
                        <option value="0">Select document to copy</option>
                        {% for document in festival.previous.documents.all %}
                            <option value="{{ document.id }}">{{ document.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button class="btn btn-primary ml-2" type="submit">Copy from {{ festival.previous.name }}</button>
            </form>
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                    <th>Filename</th>
                </tr>
            </thead>
            <tbody>
                {% for document in documents %}
                    <tr>
                        <td><a href="{% url 'content:admin_document_update' document.uuid %}">{{ document.name }}</a></td>
                        <td>{{ document.filename }}</td>
                    </tr>
                {%endfor %}
            </tbody>
        </table>
    </div>    
</div>

{% endblock %}

WebSite/templates/content/admin_image.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Image{% endblock %}

{% block content %}

    {% crispy form %}

    {% if image.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this image?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'content:admin_image_list' %}'; });
        {% if image.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'content:admin_image_delete' image.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}
        {% if initial_tab %}
            $('.nav-tabs li a[href="#{{ initial_tab }}"]').tab('show');
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/content/admin_image_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Images{% endblock %}

{% block content %}

<div class="row mb-2">
    <div class="col-3"><a href="{% url 'content:admin_image_create' %}" class="btn btn-primary">Add Image</a></div>
    <div class="col-9">
        {% if festival.previous %}
            <form class="form-inline justify-content-end" method="post" action="{% url 'content:admin_image_copy' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select class="form-control" name="copy_id">
                        <option value="0">Select image to copy</option>
                        {% for image in festival.previous.images.all %}
                            <option value="{{ image.id }}">{{ image.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button class="btn btn-primary ml-2" type="submit">Copy from {{ festival.previous.name }}</button>
            </form>
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                {% for image in images %}
                    <tr>
                        <td><a href="{% url 'content:admin_image_update' image.uuid %}">{{ image.name }}</a></td>
                    </tr>
                {%endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

WebSite/templates/content/admin_navigator.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Navigator{% endblock %}

{% block content %}

    {% crispy form %}

    {% if navigator.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this navigator?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        {% if parent %}
            let cancel_url = '{% url 'content:admin_navigator_update' parent.uuid %}';
        {% else %}
            let cancel_url = '{% url 'content:admin_navigator_list' %}';
        {% endif %}
        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = cancel_url; });
        {% if navigator.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'content:admin_navigator_delete' navigator.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}
        {% if initial_tab %}
            $('.nav-tabs li a[href="#{{ initial_tab }}"]').tab('show');
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/content/admin_page.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create/Update Page{% endblock %}

{% block content %}

    {% crispy form %}

    {% if page.can_delete %}
        <div id="tf-delete-modal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h5 class="modal-title">Confirm Delete</h5></div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this page?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary">Yes</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block body-script %}

    <script language="javascript">

        $('#button-id-cancel').addClass('btn-secondary').on('click', function () { window.location.href = '{% url 'content:admin_page_list' %}'; });
        {% if page.can_delete %}
            $('#button-id-delete').addClass('btn-danger').on('click', function() { $('#tf-delete-modal').modal('show'); });
            $('#tf-delete-modal .btn-primary').on('click', function () { window.location.href = "{% url 'content:admin_page_delete' page.uuid %}"; });
        {% else %}
            $('#button-id-delete').addClass('btn-secondary').prop('disabled', true)
        {% endif %}
        {% if initial_tab %}
            $('.nav-tabs li a[href="#{{ initial_tab }}"]').tab('show');
        {% endif %}
        {% if page %}
            $('#button-id-show-test').addClass('btn-info').on('click', function () { window.open('{% url 'content:page_test' page.uuid %}', 'TFPageTest'); });
        {% endif %}

    </script>

{% endblock %}

WebSite/templates/content/admin_page_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Pages{% endblock %}

{% block content %}

<div class="row mb-2">
    <div class="col-3"><a href="{% url 'content:admin_page_create' %}" class="btn btn-primary">Add Page</a></div>
    <div class="col-9">
        {% if festival.previous %}
            <form class="form-inline justify-content-end" method="post" action="{% url 'content:admin_page_copy' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select class="form-control" name="copy_id">
                        <option value="0">Select page to copy</option>
                        {% for page in festival.previous.pages.all %}
                            <option value="{{ page.id }}">{{ page.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button class="btn btn-primary ml-2" type="submit">Copy from {{ festival.previous.name }}</button>
            </form>
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Page</th>
                    <th>Title</th>
                </tr>
            </thead>
            <tbody>
                {% for page in pages %}
                    <tr>
                        <td><a href="{% url 'content:admin_page_update' page.uuid %}">{{ page.name }}</a></td>
                        <td>{{ page.title }}</td>
                    </tr>
                {%endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

WebSite/templates/content/admin_resource_list.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}Resources{% endblock %}

{% block content %}

<div class="row mb-2">
    <div class="col-3"><a href="{% url 'content:admin_resource_create' %}" class="btn btn-primary">Add Resource</a></div>
    <div class="col-9">
        {% if festival.previous %}
            <form class="form-inline justify-content-end" method="post" action="{% url 'content:admin_resource_copy' %}">
                {% csrf_token %}
                <div class="form-group">
                    <select class="form-control" name="copy_id">
                        <option value="0">Select resource to copy</option>
                        {% for resource in festival.previous.resources.all %}
                            <option value="{{ resource.id }}">{{ resource.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button class="btn btn-primary ml-2" type="submit">Copy from {{ festival.previous.name }}</button>
            </form>
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
                {% for resource in resources %}
                    <tr>
                        <td><a href="{% url 'content:admin_resource_update' resource.uuid %}">{{ resource.name }}</a></td>
                        <td>{{ resource.get_type_display }}</td>
                    </tr>
                {%endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

WebSite/templates/content/no_home.html
{% extends "base.html" %}
{% load i18n %}

{% block pagetitle %}No Home Page{% endblock %}

{% block content %}

    <h5>No home page defined for site</h5>

{% endblock %}

WebSite/templates/content/page.html
{% extends "base.html" %}

{% block pagetitle %}{{ page.title }}{% endblock %}

{% block content %}

    {{ body_html|safe }}

{% endblock %}